language: python
cache:
  directories:
    - $HOME/.cache/pip
matrix:
  include:
    - python: 3.6
    - python: 3.7
      dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev
script: tox

# ignore tags build
branches:
  except:
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/

#before_script:
#  - export TZ=Asia/Shanghai
#  - date
